app:
  name: "yunzhongGateWay"
logger:
  level: "debug"
  filename: "logs/app.log"
  maxSize: 100
  maxBackups: 10
  maxAge: 7
  compress: true
server:
  tcpAddr: ":2001"
  wsAddr: ":2002"
registry:
  etcdAddr:
    - "127.0.0.1:2379"

